//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromDatabase
{
    using System;
    
    public partial class Address
    {
        public string Line1 { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
    }
}
